spring.application.name=doc-ocr-server
spring.docker.compose.enabled=false

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?sslmode=require
# SSH Tunnel Configuration
ssh.bastion.host=ec2-xx-xx-xx-xx.compute-1.amazonaws.com
ssh.bastion.user=ec2-user
ssh.bastion.key-path=/path/to/your/private-key.pem
ssh.local-port=5432
ssh.remote-host=dococr.cgvqwgi4iioy.us-east-1.rds.amazonaws.com
ssh.remote-port=5432
spring.datasource.username=postgres
spring.datasource.password=$Tindu26062003