spring.application.name=doc-ocr-server
spring.docker.compose.enabled=false

spring.datasource.url=jdbc:postgresql://dococr.cgvqwgi4iioy.us-east-1.rds.amazonaws.com:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=$Tindu26062003