spring.application.name=doc-ocr-server
spring.docker.compose.enabled=false

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?sslmode=require
# SSH Tunnel Configuration
ssh.enabled=${SSH_ENABLED:false}
ssh.bastion.host=ec2-54-162-179-249.compute-1.amazonaws.com
ssh.bastion.port=22
ssh.bastion.user=ec2-user
ssh.bastion.key-path=/Users/tinduvo/Downloads/BastionHostKey.pem
ssh.local-port=5432
ssh.remote-host=dococr.cgvqwgi4iioy.us-east-1.rds.amazonaws.com
ssh.remote-port=5432
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect